;[testLogging]
;BROKER_HOST = localhost
;BROKER_PORT = 5672
;USER = test
;PASSWORD = test
;VHOST = testHost
;EXCHANGE = logExchange
;QUEUE = logQueue
;EXCHANGE_TYPE = fanout
;AUTO_DELETE = true

BROKER_HOST = localhost
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = logExchange       ; The exchange name is logExchange
EXCHANGE_TYPE = fanout       ; The exchange type is now fanout
QUEUE = logQueue
AUTO_DELETE = true
