;[testLogging]
;BROKER_HOST = localhost
;BROKER_PORT = 5672
;USER = test
;PASSWORD = test
;VHOST = testHost
;EXCHANGE = logExchange
;QUEUE = logQueue
;EXCHANGE_TYPE = fanout
;AUTO_DELETE = true

BROKER_HOST = localhost
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
logExchange = logExchange      ; Change EXCHANGE to logExchange
Fanout = fanout                ; Change EXCHANGE_TYPE to Fanout, make sure it's lowercase
QUEUE = logQueue
AUTO_DELETE = true
