[testLogging]
BROKER_HOST = 172.22.205.155
;172.22.26.72
;127.0.0.1
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = logExchange
QUEUE = logQueue
EXCHANGE_TYPE = Fanout
AUTO_DELETE = true

